# Generated by Django 3.0.3 on 2020-03-17 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0002_auto_20200316_0043'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Places',
        ),
    ]
