# Generated by Django 3.0.3 on 2020-03-17 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tourism', '0004_places'),
    ]

    operations = [
        migrations.AddField(
            model_name='places',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
